services:
  aprsc:
    build: .
    hostname: aprsc
    container_name: aprsc
    working_dir: "/opt/aprsc"
    networks:
      - aprsc-network
    volumes:
      - "./aprsc:/etc/default/aprsc"
      - "./aprsc.conf:/opt/aprsc/etc/aprsc.conf"
      - "./logs:/opt/aprsc/logs"
      - "./data:/opt/aprsc/data"
      - "./motd.html:/opt/aprsc/web/motd.html"
    ports:
      - 14501:14501/tcp
      - 8080:8080/udp
      - 8080:8080/tcp
      - 10152:10152/udp
      - 10152:10152/tcp
      - 14580:14580/udp
      - 14580:14580/tcp
      - 20350:20350/udp
      - 20350:20350/tcp
    privileged: true
    restart: unless-stopped
networks:
  aprsc-network:
    name: aprsc-network
    external: true
